shop_app/config/routes.rb
Rails.application.routes.draw do

  root 'shop#index'
  
  get '/search' => 'shop#search'
  post '/search' => 'shop#search'
  resources :shop, only: [:index, :create, :show]
  
  scope module: 'shop' do
    get 'thanks_for_order/index'
    get 'terms_conditions/index'
    get '/thanks_for_order' => 'thanks_for_order#index'

    resources :products do 
      resources :comments_product
    end
    resources :category
    resources :products, only: [:show, :update]
    resources :carts, except: %i(new edit)
    resources :checkout

    resources :transactions, controller: :checkout
    resources :terms_conditions, only: [:index]
    resources :favorites, only: [:create, :destroy]
  end

  scope module: 'article' do
    resources :articles do 
      resources :comments
    end
  end

  scope module: 'user' do
    get '/login' => 'sessions#new' 
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy' 
    get 'sign_up' => 'users#new'
    post 'sign_up' => 'users#create'
    get 'password_resets/new'
    get 'password_resets/show'

    resources :sessions, only: [:create, :destroy]
    resources :users, except: :index
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :customers
    resources :my_comments
  end
end

shop_app/app/controllers/shop/carts_controller.rb
class Shop::CartsController < BaseController
  layout 'customer'
  before_action :load_service

  def index
  end

  def create
    @service_cart.create
    flash[:success] = "Add to cart success"
    redirect_to request.referrer
  end

  def update
    @service_cart.update
    flash[:success] = "add success"
    redirect_to carts_path
  end

  def destroy
    @service_cart.destroy_item
    flash[:success] = "Delete success"
    redirect_to carts_path
  end

  private
  
  def load_service
    @service_cart = CartServices.new(params, session)
  end
end

shop_app/app/controllers/shop/category_controller.rb
class Shop::CategoryController < BaseController

  def index
  end

  def new
    @category = Category.new
  end
end

shop_app/app/controllers/shop/check_order_controller.rb
class Shop::CheckOrderController < ApplicationController
end

shop_app/app/controllers/shop/checkout_controller.rb
class Shop::CheckoutController < BaseController
  layout 'customer'
  before_action :load_service

  def create
    @service_checkout.checkout
    redirect_to thanks_for_order_path
  end

  def new
    @transaction = Transaction.new
  end

  def show
    @order_items = @service_checkout.load_order
    @transaction = @service_checkout.load_transaction
    @customer    = @service_checkout.load_customer
    @total_price = @transaction.amount
  end

  private
    def load_service
      @service_checkout = CheckoutServices.new(params, @service_user.current_user, load_cart, @total, session)
    end
end

shop_app/app/controllers/shop/comments_product_controller.rb
class Shop::CommentsProductController <  BaseController
  before_action :load_service

  def new
    @comment = Comment.new
  end

  def create
    @service_comment_product.create
    product = @service_comment_product.find_product
    redirect_to product_path(product)
  end

  def destroy
    @service_comment_product.destroy
    product = @service_comment_product.find_product
    redirect_to product_path(product)
  end

  private
    def load_service
      @service_comment_product = CommentProductServices.new(params, flash, @service_user.current_user)
    end
end

shop_app/app/controllers/shop/favorites_controller.rb
class Shop::FavoritesController < BaseController
  before_action :load_service

  def new
    @favorite = Favorite.new
  end

  def create
    @service_favorite.create_favorite
    redirect_to request.referrer
  end
 
  def destroy
    @service_favorite.destroy_favorite
    redirect_to request.referrer
  end

  private
  def load_service
    @service_favorite = FavoritesServices.new(params, @service_user.current_user)
  end
end

shop_app/app/controllers/shop/new_user_checkout_controller.rb
class Shop::NewUserCheckoutController < ApplicationController
end

shop_app/app/controllers/shop/products_controller.rb
class Shop::ProductsController < BaseController
  layout 'customer'
  before_action :load_service

  def index
    @products = Product.all
  end

  def update
  end

  def show
    @product = load_product
    @category = Category.find_by(id: @product.category_id)
    @price = @product.product_options
    @sizes = @product.sizes.distinct
    @types = @product.types.distinct
    @comment = Comment.new
    @comments = @product.comment_products.where(
          parent_id: 0).paginate page: params[:page], per_page: 3
    @productSuggest = Product.where(category_id: @product.category_id,status: "exist")
                             .order(like: :desc).first(3)
  end

  private
    def load_product
      Product.find_by(id: params[:id], status: "exist")
    end

    def load_service
      @service_favorite = FavoritesServices.new(params, @service_user.current_user)
    end
end

shop_app/app/controllers/shop/terms_conditions_controller.rb
class Shop::TermsConditionsController < BaseController
  layout 'customer'
  def index
  end
end

shop_app/app/controllers/shop/thanks_for_order_controller.rb
class Shop::ThanksForOrderController < BaseController
  layout 'customer'

  def index
    if session[:transaction_id]
      @order_items = Order.where(transaction_id: session[:transaction_id])
      @transaction = Transaction.find_by(id: session[:transaction_id])
      @customer    = Customer.find_by(id: @transaction.customer_id)
      @total_price = @transaction.amount
    end
  end
end

shop_app/app/controllers/shop_controller.rb
class ShopController < BaseController
  before_action :logged_in?
  before_action :load_service
  
  def index
    @categories = list_find_category
    @productList = Product.where(status: "exist").paginate page: params[:page],
            per_page: 9
    @order_details = []
    @count_products = 0
    @total = 0
    @len = Product.all.size
    @productSuggest = Product.where(status: "exist")
                            .order(like: :desc).first(3)
  end

  def create
  end

  def search
    @categories = list_find_category
    @listProduct = @service_shop.search_product
  end

  def show
    @categories = list_find_category
    @productByCategory = Product.where(category_id: params[:id],status: "exist")
                        .paginate page: params[:page], per_page: 9
    @lengh = Product.where(category_id: params[:id]).size
  end 

  private
    def list_find_category
      Category.where(parent_id: 0, status: "exist")
    end 

    def load_service
      @service_shop     = ShopServices.new(params)
      @service_favorite = FavoritesServices.new(params, @service_user.current_user)
    end
end

shop_app/app/helpers/shop_helper.rb
module ShopHelper
end

shop_app/app/views/shop/index.html.erb
<% content_for :title, 'Shop Cafe' %>
<% content_for :script, javascript_include_tag(:shop) %>

<div class="row featuredPostContainer style2">
  <h3 class="section-title style2 text-center">
    <span>SUGGEST PRODUCTs</span>
  </h3>
  <div class="row  categoryProduct xsResponse clearfix">
    <% @productSuggest.each do |product| %>
      <div class="item col-sm-4 col-lg-4 col-md-4 col-xs-6" 
        style="height: 476px; display: flex;">
        <div class="product">
          <% if @service_user.current_user %>
            <% if @service_favorite.check_like(@service_user.current_user.id, product.id).nil? %>
              <div class="favorite"
                id="product_<%= product.id %>", style= "width: 50px;">
                <%= form_with(url: favorites_path, method: :post, local: true) do |form| %>
                  <%= form.hidden_field :user_id, 
                    value: @service_user.current_user.id %>
                  <%= form.hidden_field :product_id, value: product.id %>
                  <button type="submit">
                    <i class="far fa-heart"></i>
                    <span><%= product.like ? product.like : 0 %></span>
                  </button>
                <% end %>
              </div>
            <% else %>
              <div class="favorite"
                id="product_<%= product.id %>">
                <%= form_with(url: favorite_path(@service_favorite.check_like(
                  @service_user.current_user.id, product.id)), method: :delete,local: true) do |form| %>
                  <%= form.hidden_field :user_id, value: @service_user.current_user.id %>
                  <%= form.hidden_field :product_id, value: product.id %>
                  <button type="submit">
                    <i class="fas fa-heart"></i>
                    <span><%= product.like ? product.like : 0 %></span>
                  </button>
                <% end %>
              </div>
            <% end %>
          <% else %>
            <div class="favorite">
              <button type="submit" disabled>
                <i class="fas fa-heart"></i>
                <span><%= product.like ? product.like : 0 %></span>
              </button>
            </div>  
          <% end %>
          <div class="image" style="height: 200px; width: 260px">
            <%= link_to product_path(product) do %>
              <%= cl_image_tag product.image_link, alt: 'img',  height: "200px",
                width: "262px"  %>
            <% end %>
            <div class="promotion"><span class="new-product"> NEW</span><%#= product.discount%></div>
          </div>
          <div class="description">
            <h4><%= product.name %></h4>
              <p><%= product.description%></p>
            <span class="size"><%= product.sizes.first.name %></span>
          </div>
          <div class="price">
            <span class="price"><%= product.product_options.first.price %>$
            </span>
          </div>
          <div class="action-control">
            <%= form_with scope: :cart, url: carts_path, local: true do |form| %>
              <%= form.hidden_field :price, value: product.product_options.first.price %>
              <%= form.hidden_field :size, value: product.sizes.first.name %>
              <%= form.hidden_field :type, value: product.types.first.name %>
              <%= form.hidden_field :product_id, value: product.id %>
              <%= form.hidden_field :quantity, value: 1 %>
              <%= form.submit 'Add to Cart', class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div> 
</div>

<div class="row featuredPostContainer style2">
  <h3 class="section-title style2 text-center">
    <span>LIST PRODUCTs</span>
  </h3>
  <div class="w100  clearfix">
    <p class="pull-left"> Showing <strong><%= @productList.length %></strong> products </p>
  </div>
  <div class="row  categoryProduct xsResponse clearfix">
    <% @productList.each do |product| %>
      <div class="item col-sm-4 col-lg-4 col-md-4 col-xs-6" 
        style="height: 476px; display: flex;">
        <div class="product">
          <% if @service_user.current_user %>
            <% if @service_favorite.check_like(@service_user.current_user.id, product.id).nil? %>
              <div class="favorite"
                id="product_<%= product.id %>", style= "width: 50px;">
                <%= form_with(url: favorites_path, method: :post, local: true) do |form| %>
                  <%= form.hidden_field :user_id, 
                    value: @service_user.current_user.id %>
                  <%= form.hidden_field :product_id, value: product.id %>
                  <button type="submit">
                    <i class="far fa-heart"></i>
                    <span><%= product.like ? product.like : 0 %></span>
                  </button>
                <% end %>
              </div>
            <% else %>
              <div class="favorite"
                id="product_<%= product.id %>">
                <%= form_with(url: favorite_path(@service_favorite.check_like(
                  @service_user.current_user.id, product.id)), method: :delete,local: true) do |form| %>
                  <%= form.hidden_field :user_id, value: @service_user.current_user.id %>
                  <%= form.hidden_field :product_id, value: product.id %>
                  <button type="submit">
                    <i class="fas fa-heart"></i>
                    <span><%= product.like ? product.like : 0 %></span>
                  </button>
                <% end %>
              </div>
            <% end %>
          <% else %>
            <div class="favorite">
              <button type="submit" disabled>
                <i class="fas fa-heart"></i>
                <span><%= product.like ? product.like : 0 %></span>
              </button>
            </div>  
          <% end %>
          <div class="image" style="height: 200px; width: 260px">
            <%= link_to product_path(product) do %>
              <%= cl_image_tag product.image_link, alt: 'img',  height: "200px",
                width: "262px"  %>
            <% end %>
            <div class="promotion"><span class="new-product"> NEW</span><%#= product.discount%></div>
          </div>
          <div class="description">
            <h4><%= product.name %></h4>
              <p><%= product.description%></p>
            <span class="size"><%= product.sizes.first.name %></span>
          </div>
          <div class="price">
            <span class="price"><%= product.product_options.first.price %>$
            </span>
          </div>
          <div class="action-control">
            <%= form_with scope: :cart, url: carts_path, local: true do |form| %>
              <%= form.hidden_field :price, value: product.product_options.first.price %>
              <%= form.hidden_field :size, value: product.sizes.first.name %>
              <%= form.hidden_field :type, value: product.types.first.name %>
              <%= form.hidden_field :product_id, value: product.id %>
              <%= form.hidden_field :quantity, value: 1 %>
              <%= form.submit 'Add to Cart', class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div> 
</div>  
<div class="row categoryFooter">
  <div class="col-lg-offset-4 col-lg-8 ">
    <%= will_paginate(@productList, renderer: BootstrapPagination::Rails)%>
  </div>
</div>

shop_app/app/views/shop/search.html.erb
<% content_for :title, 'Search' %>
<% content_for :script, javascript_include_tag(:shop) %>

<% if @listProduct %>
<%# binding.pry %>
  <div class="w100 productFilter clearfix">
    <h2 class="pull-left"> Showing <strong><%= @listProduct.length %></strong> products </h2>
  </div>

  <div class="row  categoryProduct xsResponse clearfix">
    <% @listProduct.each do |product| %>
      <div class="item col-sm-4 col-lg-4 col-md-4 col-xs-6" 
        style="height: 476px; display: flex;">
        <div class="product">
            <% if @service_user.current_user %>
          <% if @service_favorite.check_like(@service_user.current_user.id, product.id).nil? %>
            <div class="favorite"
              id="product_<%= product.id %>", style= "width: 50px;">
              <%= form_with(url: favorites_path, method: :post, local: true) do |form| %>
                <%= form.hidden_field :user_id, 
                  value: @service_user.current_user.id %>
                <%= form.hidden_field :product_id, value: product.id %>
                <button type="submit">
                  <i class="far fa-heart"></i>
                  <span><%= product.like ? product.like : 0 %></span>
                </button>
              <% end %>
            </div>
          <% else %>
            <div class="favorite"
              id="product_<%= product.id %>">
              <%= form_with(url: favorite_path(@service_favorite.check_like(
                @service_user.current_user.id, product.id)), method: :delete,local: true) do |form| %>
                <%= form.hidden_field :user_id, value: @service_user.current_user.id %>
                <%= form.hidden_field :product_id, value: product.id %>
                <button type="submit">
                  <i class="fas fa-heart"></i>
                  <span><%= product.like ? product.like : 0 %></span>
                </button>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <div class="favorite">
            <button type="submit" disabled>
              <i class="fas fa-heart"></i>
              <span><%= product.like ? product.like : 0 %></span>
            </button>
          </div>  
        <% end %>

          <div class="image">
            <%= link_to product_path(product) do %>
              <%= cl_image_tag product.image_link, alt: 'img', height: "200px",
              width: "262px" %>
            <% end %>
            <div class="promotion"><span class="new-product"> NEW</span><%#= product.discount%></div>
          </div>
          <div class="description">
            <h4><%= product.name %></a></h4>
              <p><%= product.description%></p>
            <span class="size"><%= product.sizes.first.name %></span>
          </div>
          <div class="price">
            <span class="price"><%= product.product_options.first.price %>$</span>
          </div>
          <div class="action-control">
            <%= form_with scope: :cart, url: carts_path, local: true do |form| %>
              <%= form.hidden_field :size, value: product.sizes.pluck(:name).join %>
              <%= form.hidden_field :type, value: product.types.pluck(:name).join %>
              <%= form.hidden_field :product_id, value: product.id %>
              <%= form.hidden_field :quantity, value: 1 %>
              <%= form.submit 'Add to Cart', class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  
  <div class="row categoryFooter">
    <div class="col-lg-offset-4 col-lg-8 ">
      <%#= will_paginate(@productList, renderer: BootstrapPagination::Rails) %>
    </div>
  </div>
<% else %>
  <h2 class="pull-left"> Showing <strong>0 matching results</strong> </h2>
<% end %>

shop_app/app/views/shop/show.html.erb
<% content_for :title, @categories.name %>
<% content_for :script, javascript_include_tag(:shop) %>

<div class="w100 productFilter clearfix">
  <p class="pull-left"> Showing <strong><%= @productByCategory.size %></strong> products </p>
</div>

<div class="row  categoryProduct xsResponse clearfix">
  <% @productByCategory.each do |product| %>
    <div class="item col-sm-4 col-lg-4 col-md-4 col-xs-6" 
      style="height: 476px; display: flex;">
      <div class="product">
        <% if @service_user.current_user %>
          <% if @service_favorite.check_like(@service_user.current_user.id, product.id).nil? %>
            <div class="favorite"
              id="product_<%= product.id %>", style= "width: 50px;">
              <%= form_with(url: favorites_path, method: :post, local: true) do |form| %>
                <%= form.hidden_field :user_id, 
                  value: @service_user.current_user.id %>
                <%= form.hidden_field :product_id, value: product.id %>
                <button type="submit">
                  <i class="far fa-heart"></i>
                  <span><%= product.like ? product.like : 0 %></span>
                </button>
              <% end %>
            </div>
          <% else %>
            <div class="favorite"
              id="product_<%= product.id %>">
              <%= form_with(url: favorite_path(@service_favorite.check_like(
                @service_user.current_user.id, product.id)), method: :delete,local: true) do |form| %>
                <%= form.hidden_field :user_id, value: @service_user.current_user.id %>
                <%= form.hidden_field :product_id, value: product.id %>
                <button type="submit">
                  <i class="fas fa-heart"></i>
                  <span><%= product.like ? product.like : 0 %></span>
                </button>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <div class="favorite">
            <button type="submit" disabled>
              <i class="fas fa-heart"></i>
              <span><%= product.like ? product.like : 0 %></span>
            </button>
          </div>  
        <% end %>

        <div class="image" style="height: 200px; width: 260px">
          <%= link_to product_path(product) do %>
            <%= cl_image_tag product.image_link, alt: 'img', height: "200px",
              width: "262px"%>
          <% end %>
          <div class="promotion"><span class="new-product"> NEW</span><%#= product.discount%></div>
        </div>
        <div class="description">
          <h4><%= product.name %></a></h4>
            <p><%= product.description%></p>
          <span class="size"><%= product.sizes.first.name %></span>
        </div>
        <div class="price">
          <span class="price"><%= product.product_options.first.price %>$</span>
        </div>
        <div class="action-control">
          <%= form_with scope: :cart, url: carts_path, local: true do |form| %>
            <%= form.hidden_field :price, value: product.product_options.first.price %>
            <%= form.hidden_field :size, value: product.sizes.first.name %>
            <%= form.hidden_field :type, value: product.types.first.name %>
            <%= form.hidden_field :product_id, value: product.id %>
            <%= form.hidden_field :quantity, value: 1 %>
            <%= form.submit 'Add to Cart', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
  <% if @lengh < 10 %>
    <div class="row categoryFooter">
      <div class="col-lg-offset-4 col-lg-8 ">
        <ul class="pagination pagination">
          <li class="prev disabled"><span>&#8592; Previous</span></li>
          <li class="active"><span>1</span></li> 
          <li class="next"><a>Next &#8594;</a></li>
        </ul>
      </div>
    </div>
  <% end %> 
  <div class="col-lg-offset-4 col-lg-8 ">
    <%= will_paginate(@productByCategory, renderer: BootstrapPagination::Rails) %>
  </div>
</div>